Add -m flag which allows to modify branch together with Jira issue summary
macanton/got pull request #3
Opened 2020-11-15 13:28 UTC by macanton

## Summary
Current PR adds possibility to modify current branch issue together with current branch name

## Usage
```
got -m
Enter Jira issue summary: 
```

## Checklist
- checkout to branch which is already linked to Jira issue
- execute `got -m`
- enter new Jira issue summary
- check that issue updated and that branch name updated

- checkout to branch which is already linked to several Jira issues
- execute `got -m`
- enter new Jira issue summary
- check that first issue updated and that branch name updated

- checkout to branch wich is not linked to jira issue
- execute `got -m`
- enter new Jira issue summary
- should return an error

2020-11-18 12:22 UTC, Den1k22 requested changes

2020-11-18 12:22 UTC, Den1k22 commented on pkg/git/commands.go
> +func GetCurrentBranch() (string, error) {
What do you think to be more specific and call this function: `GetCurrentBranchName`

2020-11-18 12:22 UTC, Den1k22 commented on main.go
> +	printInfoToConsole(fmt.Sprintf("Jira issue summary updated to '%s'", config.Options.Summary))
What about to use `summary` instead of `config.Options.Summary`

2020-11-19 08:18 UTC, macanton commented on pkg/git/commands.go
> +func GetCurrentBranch() (string, error) {
Sounds good. With that change we can have a set of functions that operate with `Branch struct` in future

2020-11-19 08:49 UTC, Den1k22 approved these changes

2020-11-19 08:50 UTC, merged